server:
 port: 8086

spring:
 datasource:
  url: jdbc:mysql://localhost:3306/tb_ocean?useServerPrepStmts=false&useUnicode=true&characterEncoding=UTF-8
  username : root
  password: 123456789
  driver-class-name: com.mysql.cj.jdbc.Driver

logging:
 level:
  com.example.demo.mapper: debug




